name: frontend
description: "Direction-aware vehicle counting app"
publish_to: 'none' 

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  country_flags: ^4.0.0
  file_picker: ^10.3.8
  flutter_colorpicker: ^1.0.3
  provider: ^6.0.5
  path: ^1.8.3
  loading_animation_widget:
  hive_flutter: ^1.1.0
  system_theme: ^3.2.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0
  media_kit: ^1.2.6 
  media_kit_video: ^2.0.1 
  media_kit_libs_video: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2 
  cupertino_icons: ^1.0.8
  navigator: ^1.1.1
  uuid: ^4.5.2
  shared_preferences: ^2.5.3
  analyzer_plugin: ^0.13.7
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true  
  assets:
    - assets/localization/
    - assets/images/
    - assets/animation/

l10n:
  arb-dir: assets/localization
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-dir: lib/src/localization