name: frontend
description: "Direction-aware vehicle counting app"
publish_to: 'none' 

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  country_flags: ^4.0.0
  file_picker: ^6.1.1
  flutter_colorpicker: ^1.0.3
  provider: ^6.0.5
  path: ^1.8.3
  google_fonts: ^6.1.0
  http: ^1.6.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  cupertino_icons: ^1.0.8
  navigator: ^1.1.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true  
  assets:
    - assets/localization/
    - assets/images/